import type { NewsArticle } from "./types";
import { NEWS_SOURCES } from "./preferences";

// ============================================================
//  示例新闻数据 (Mock Data)
//  ----------------------------------------------------------
//  演示用样例数据，模拟按选文方向筛选的全球政经新闻。
//  包含 AIIB 专题追踪与 Peer Highlights 机构报道。
//  后续接入真实新闻 API / Google 搜索时，替换 getNews() 实现即可。
// ============================================================

type MockArticle = Omit<NewsArticle, "sourceName">;

const RAW_MOCK_ARTICLES: MockArticle[] = [
  // ========== AIIB 专题 ==========
  {
    id: "aiib-001",
    title: "AIIB Approves $500 Million Loan for Southeast Asia Green Energy Corridor",
    url: "https://www.reuters.com/world/asia-pacific/aiib-green-energy-corridor-loan-2026/",
    sourceId: "reuters",
    publishedAt: "2026-07-28T07:15:00Z",
    category: "multilateral",
    summary: "The AIIB board approved financing for a cross-border renewable energy transmission project linking Vietnam, Laos and Thailand, the bank's largest green infrastructure commitment to date.",
    region: "Asia",
    entityIds: ["aiib"],
  },
  {
    id: "aiib-002",
    title: "AIIB and World Bank Sign Co-Financing MoU to Scale Climate Adaptation Projects",
    url: "https://www.ft.com/content/aiib-world-bank-climate-cofinancing-2026",
    sourceId: "ft",
    publishedAt: "2026-07-26T13:40:00Z",
    category: "multilateral",
    summary: "AIIB and the World Bank Group signed a memorandum to jointly mobilize private capital for climate adaptation, targeting $10 billion in blended finance over five years.",
    region: "Global",
    entityIds: ["aiib", "wbg"],
  },
  {
    id: "aiib-003",
    title: "AIIB Expands Membership as Three New Countries Join the Beijing-Based Lender",
    url: "https://asia.nikkei.com/Spotlight/aiib-membership-expansion-2026",
    sourceId: "nikkei",
    publishedAt: "2026-07-24T02:30:00Z",
    category: "multilateral",
    summary: "AIIB welcomed new members from Latin America and Africa, bringing total membership to 110 countries and expanding its lending capacity for sustainable infrastructure.",
    region: "Global",
    entityIds: ["aiib"],
  },
  {
    id: "aiib-004",
    title: "AIIB Annual Report Shows Record Lending Despite Global Headwinds",
    url: "https://www.bloomberg.com/news/articles/2026-07-22-aiib-annual-report-lending",
    sourceId: "bloomberg",
    publishedAt: "2026-07-22T11:00:00Z",
    category: "multilateral",
    summary: "AIIB reported $12 billion in annual project approvals, with AIIB management citing strong demand for climate finance and digital infrastructure across developing economies.",
    region: "Global",
    entityIds: ["aiib"],
  },

  // ========== 全球政经要事 ==========
  {
    id: "ga-001",
    title: "US-Iran Tensions Escalate After Strait of Hormuz Incident Disrupts Shipping",
    url: "https://www.reuters.com/world/middle-east/us-iran-strait-of-hormuz-2026/",
    sourceId: "reuters",
    publishedAt: "2026-07-28T09:00:00Z",
    category: "global-affairs",
    summary: "The US deployed additional naval assets after Iran seized a commercial tanker, raising fears of a broader confrontation in one of the world's most critical oil chokepoints.",
    region: "Middle East",
    entityIds: [],
  },
  {
    id: "ga-002",
    title: "Russia-Ukraine Peace Talks Resume as Mediators Push for 30-Day Truce",
    url: "https://www.bbc.com/news/world-europe-russia-ukraine-peace-talks-2026",
    sourceId: "bbc",
    publishedAt: "2026-07-27T15:20:00Z",
    category: "global-affairs",
    summary: "Diplomats from both sides met in Istanbul for the first time in eight months, with Turkey and the UN mediating a framework for a temporary ceasefire.",
    region: "Europe",
    entityIds: [],
  },
  {
    id: "ga-003",
    title: "US-China High-Level Dialogue Aims to Stabilize Ties Amid Tech Export Controls",
    url: "https://www.nytimes.com/2026/07/26/world/asia/us-china-dialogue-tech-controls.html",
    sourceId: "nyt",
    publishedAt: "2026-07-26T10:30:00Z",
    category: "global-affairs",
    summary: "Secretary of State and China's foreign minister held extended talks on semiconductor export controls, Taiwan Strait stability, and resuming military-to-military communication.",
    region: "Asia",
    entityIds: [],
  },
  {
    id: "ga-004",
    title: "Middle East Ceasefire Framework Endorsed by UN Security Council",
    url: "https://apnews.com/article/un-security-council-middle-east-ceasefire-2026",
    sourceId: "ap",
    publishedAt: "2026-07-25T19:45:00Z",
    category: "global-affairs",
    summary: "The 15-member council voted unanimously to endorse a phased ceasefire, with monitoring by a multinational force and commitments to reconstruction funding.",
    region: "Middle East",
    entityIds: [],
  },
  {
    id: "ga-005",
    title: "NATO Summit Approves New Defense Spending Pledge at 2.5% of GDP",
    url: "https://www.wsj.com/world/europe/nato-defense-spending-2-5-percent-2026",
    sourceId: "wsj",
    publishedAt: "2026-07-24T16:00:00Z",
    category: "global-affairs",
    summary: "Alliance members committed to raising defense budgets to 2.5% of GDP within five years, reflecting sustained pressure from the Russia-Ukraine conflict.",
    region: "Europe",
    entityIds: [],
  },

  // ========== 国际贸易与政策 ==========
  {
    id: "tp-001",
    title: "EU Adjusts Steel Tariffs in Bid to Shield Industry from Import Surge",
    url: "https://www.ft.com/content/eu-steel-tariffs-adjustment-2026",
    sourceId: "ft",
    publishedAt: "2026-07-27T14:00:00Z",
    category: "trade-policy",
    summary: "The European Commission revised its tariff-rate quota system for steel imports, extending safeguards while adjusting allocations to reflect changing trade flows.",
    region: "Europe",
    entityIds: [],
  },
  {
    id: "tp-002",
    title: "UK and GCC Finalize Landmark Free Trade Agreement After Two-Year Talks",
    url: "https://www.reuters.com/world/uk/uk-gcc-trade-agreement-2026/",
    sourceId: "reuters",
    publishedAt: "2026-07-26T08:50:00Z",
    category: "trade-policy",
    summary: "The deal eliminates tariffs on 99% of goods traded between the UK and the six Gulf states, projected to boost bilateral trade by £16 billion annually.",
    region: "Global",
    entityIds: [],
  },
  {
    id: "tp-003",
    title: "EU Pushes Supply Chain Diversification with New Critical Raw Materials Act",
    url: "https://www.theguardian.com/business/2026/jul/25/eu-critical-raw-materials-act",
    sourceId: "guardian",
    publishedAt: "2026-07-25T11:30:00Z",
    category: "trade-policy",
    summary: "The legislation mandates strategic stockpiles of 34 critical minerals and streamlines permitting for domestic mining and processing to reduce China dependence.",
    region: "Europe",
    entityIds: [],
  },
  {
    id: "tp-004",
    title: "US Extends Chip Export Controls to Cover Advanced Packaging Technologies",
    url: "https://www.bloomberg.com/news/articles/2026-07-23-us-chip-export-controls",
    sourceId: "bloomberg",
    publishedAt: "2026-07-23T17:15:00Z",
    category: "trade-policy",
    summary: "The Commerce Department expanded restrictions on advanced semiconductor packaging equipment sales to China, closing loopholes in the previous rules.",
    region: "Global",
    entityIds: [],
  },
  {
    id: "tp-005",
    title: "G20 Backs Overhaul of Investment Rules to Channel Capital to Developing Nations",
    url: "https://www.economist.com/finance-and-economics/2026/07/22/g20-investment-rules",
    sourceId: "economist",
    publishedAt: "2026-07-22T12:00:00Z",
    category: "trade-policy",
    summary: "Finance ministers endorsed new guidelines to reduce investment barriers and improve dispute-resolution mechanisms, aiming to unlock $200 billion in cross-border capital flows.",
    region: "Global",
    entityIds: [],
  },

  // ========== 亚太政经动态 ==========
  {
    id: "ap-001",
    title: "India's GDP Grows 7.2% as Manufacturing Investment Surge Continues",
    url: "https://asia.nikkei.com/Economy/india-gdp-manufacturing-investment-2026",
    sourceId: "nikkei",
    publishedAt: "2026-07-27T23:00:00Z",
    category: "asia-pacific",
    summary: "Strong capital expenditure and a production-linked incentive scheme drove the fastest growth among major economies, with electronics manufacturing leading gains.",
    region: "Asia",
    entityIds: [],
  },
  {
    id: "ap-002",
    title: "Samsung Reaches Wage Agreement with Union, Averting Major Strike Risk",
    url: "https://www.reuters.com/technology/samsung-union-wage-agreement-2026/",
    sourceId: "reuters",
    publishedAt: "2026-07-26T06:30:00Z",
    category: "asia-pacific",
    summary: "South Korea's largest chipmaker agreed to a 5.1% wage increase and expanded benefits, ending a standoff that had threatened global memory chip supply.",
    region: "Asia",
    entityIds: [],
  },
  {
    id: "ap-003",
    title: "Japan Approves Financing Framework to Expand Domestic Defense Industry",
    url: "https://www.wsj.com/world/asia/japan-defense-industry-financing-2026",
    sourceId: "wsj",
    publishedAt: "2026-07-25T13:10:00Z",
    category: "asia-pacific",
    summary: "The government unveiled a state-backed financing program to help defense contractors scale production, including missiles and naval vessels, to meet new security demands.",
    region: "Japan",
    entityIds: [],
  },
  {
    id: "ap-004",
    title: "Vietnam Commissions 3.2 GW Offshore Wind Farm, Largest in Southeast Asia",
    url: "https://www.scmp.com/week-asia/economy/article/vietnam-offshore-wind-2026",
    sourceId: "scmp",
    publishedAt: "2026-07-24T09:45:00Z",
    category: "asia-pacific",
    summary: "The project marks a milestone in regional energy transition, with cross-border power purchase agreements enabling exports to Singapore under the ASEAN power grid plan.",
    region: "Asia",
    entityIds: [],
  },
  {
    id: "ap-005",
    title: "China's Industrial Output Rises 5.8% as Tech Upgrade Drive Gains Traction",
    url: "https://www.caixinglobal.com/economy/china-industrial-output-2026/",
    sourceId: "caixin",
    publishedAt: "2026-07-23T03:20:00Z",
    category: "asia-pacific",
    summary: "High-tech manufacturing and new-energy vehicle production outpaced traditional sectors, reflecting Beijing's push up the value chain amid trade pressures.",
    region: "China",
    entityIds: [],
  },

  // ========== 金融市场 ==========
  {
    id: "mk-001",
    title: "Federal Reserve Signals September Rate Cut as Inflation Hits 2.1%",
    url: "https://www.bloomberg.com/news/articles/2026-07-28-fed-rate-cut-september",
    sourceId: "bloomberg",
    publishedAt: "2026-07-28T18:00:00Z",
    category: "markets",
    summary: "Chair Powell indicated the central bank could begin cutting rates at the next meeting, with core PCE inflation approaching the 2% target and labor market cooling.",
    region: "United States",
    entityIds: ["imf"],
  },
  {
    id: "mk-002",
    title: "Global Bond Yields Fall as Investors Price in Easing Cycle Across Major Economies",
    url: "https://www.ft.com/content/global-bond-yields-easing-cycle-2026",
    sourceId: "ft",
    publishedAt: "2026-07-27T16:30:00Z",
    category: "markets",
    summary: "The 10-year US Treasury yield dropped below 3.8%, while German bunds and Japanese JGBs also rallied as markets anticipated coordinated monetary loosening.",
    region: "Global",
    entityIds: [],
  },
  {
    id: "mk-003",
    title: "Gold Hits Record High Above $2,600 on Geopolitical Risk and Rate-Cut Bets",
    url: "https://www.reuters.com/markets/commodities/gold-record-high-2026/",
    sourceId: "reuters",
    publishedAt: "2026-07-26T14:00:00Z",
    category: "markets",
    summary: "Spot gold extended its rally as escalating Middle East tensions and expectations of lower US real rates boosted demand for safe-haven assets.",
    region: "Global",
    entityIds: [],
  },
  {
    id: "mk-004",
    title: "Oil Prices Surge Past $95 as Hormuz Disruption Threatens Supply",
    url: "https://www.wsj.com/markets/energy/oil-prices-hormuz-disruption-2026",
    sourceId: "wsj",
    publishedAt: "2026-07-25T20:30:00Z",
    category: "markets",
    summary: "Brent crude jumped 4% on news of shipping disruptions in the Strait of Hormuz, with analysts warning that sustained escalation could push prices above $100.",
    region: "Global",
    entityIds: [],
  },
  {
    id: "mk-005",
    title: "Dollar Weakens to 14-Month Low as Rate-Cut Expectations Build",
    url: "https://www.cnbc.com/2026/07/24/dollar-weakens-rate-cut-expectations.html",
    sourceId: "cnn",
    publishedAt: "2026-07-24T17:00:00Z",
    category: "markets",
    summary: "The dollar index fell to its lowest level since mid-2025, fueling rallies in emerging market currencies and commodity prices denominated in greenbacks.",
    region: "Global",
    entityIds: [],
  },

  // ========== 多边开发机构 (Peer Highlights) ==========
  {
    id: "ml-001",
    title: "World Bank Approves $3 Billion Package for Climate-Resilient Infrastructure in Africa",
    url: "https://www.reuters.com/world/africa/world-bank-climate-infrastructure-africa-2026/",
    sourceId: "reuters",
    publishedAt: "2026-07-27T10:00:00Z",
    category: "multilateral",
    summary: "The World Bank Group unveiled its largest-ever climate adaptation package for Sub-Saharan Africa, blending concessional loans with private capital mobilization.",
    region: "Africa",
    entityIds: ["wbg"],
  },
  {
    id: "ml-002",
    title: "IMF Upgrades Global Growth Forecast, Warns on Debt Sustainability",
    url: "https://apnews.com/article/imf-global-growth-forecast-2026",
    sourceId: "ap",
    publishedAt: "2026-07-26T14:30:00Z",
    category: "multilateral",
    summary: "The IMF raised its 2026 growth projection to 3.4% but cautioned that rising debt servicing costs threaten fiscal stability in over 60 developing nations.",
    region: "Global",
    entityIds: ["imf"],
  },
  {
    id: "ml-003",
    title: "ADB Launches $5 Billion Energy Transition Financing Facility for Asia",
    url: "https://asia.nikkei.com/Economy/adb-energy-transition-facility-2026",
    sourceId: "nikkei",
    publishedAt: "2026-07-25T06:00:00Z",
    category: "multilateral",
    summary: "The Asian Development Bank established a new facility to accelerate coal-to-clean transitions, combining loans, guarantees, and risk-sharing instruments.",
    region: "Asia",
    entityIds: ["adb"],
  },
  {
    id: "ml-004",
    title: "EIB and EBRD Jointly Back €2 Billion Ukraine Reconstruction Fund",
    url: "https://www.dw.com/en/eib-ebrd-ukraine-reconstruction-fund/a-69000001",
    sourceId: "dw",
    publishedAt: "2026-07-24T12:15:00Z",
    category: "multilateral",
    summary: "The two European lenders pooled resources to finance energy grid restoration and housing rebuilding, emphasizing private capital mobilization and debt transparency.",
    region: "Europe",
    entityIds: ["eib", "ebrd"],
  },
  {
    id: "ml-005",
    title: "AfDB Mobilizes $1.5 Billion in Private Capital for Renewable Energy",
    url: "https://www.ft.com/content/afdb-private-capital-renewable-energy-2026",
    sourceId: "ft",
    publishedAt: "2026-07-23T09:30:00Z",
    category: "multilateral",
    summary: "The African Development Bank Group announced a blended-finance breakthrough, attracting institutional investors to solar and wind projects across the continent.",
    region: "Africa",
    entityIds: ["afdb"],
  },
  {
    id: "ml-006",
    title: "SCO Summit Endorses Framework for Cross-Border Infrastructure Investment",
    url: "https://www.scmp.com/news/china/diplomacy/article/sco-infrastructure-investment-2026",
    sourceId: "scmp",
    publishedAt: "2026-07-22T08:00:00Z",
    category: "multilateral",
    summary: "Shanghai Cooperation Organization members agreed on investment rules to finance transit corridors and energy links, with a focus on debt management safeguards.",
    region: "Asia",
    entityIds: ["sco"],
  },
  {
    id: "ml-007",
    title: "NDB Issues First Green Bond in Local Currencies to Fund Sustainable Cities",
    url: "https://www.bloomberg.com/news/articles/2026-07-21-ndb-green-bond-local-currency",
    sourceId: "bloomberg",
    publishedAt: "2026-07-21T15:00:00Z",
    category: "multilateral",
    summary: "The New Development Bank priced a multi-currency green bond to finance urban infrastructure in BRICS nations, reducing foreign-exchange risk for borrowers.",
    region: "Global",
    entityIds: ["ndb"],
  },
  {
    id: "ml-008",
    title: "IDB and IsDB Partner on $800 Million Islamic Finance Facility for Latin America",
    url: "https://www.reuters.com/world/americas/idb-isdb-islamic-finance-latin-america-2026/",
    sourceId: "reuters",
    publishedAt: "2026-07-20T13:00:00Z",
    category: "multilateral",
    summary: "The Inter-American Development Bank and Islamic Development Bank launched a joint sukuk-based facility to fund infrastructure and energy projects in member states.",
    region: "Global",
    entityIds: ["idb", "isdb"],
  },

  // ========== 地区补充：日韩印澳欧 ==========
  {
    id: "reg-001",
    title: "Japan's Defense Budget Hits Record as Cabinet Approves Major Spending Increase",
    url: "https://www.japantimes.co.jp/news/2026/07/japan-defense-budget-record/",
    sourceId: "japantimes",
    publishedAt: "2026-07-27T01:30:00Z",
    category: "asia-pacific",
    summary: "The cabinet approved a 7.5 trillion yen defense budget, funding missile defense and naval expansion amid escalating regional security concerns.",
    region: "Japan",
    entityIds: [],
  },
  {
    id: "reg-002",
    title: "Korea Times: Samsung's $200 Billion Chip Investment Plan Targets Advanced Nodes",
    url: "https://www.koreatimes.co.kr/www/tech/2026/07/samsung-chip-investment.html",
    sourceId: "koreatimes",
    publishedAt: "2026-07-26T03:00:00Z",
    category: "asia-pacific",
    summary: "Samsung announced a decade-long investment to build next-generation semiconductor fabs, positioning Korea against Taiwan and the US in the chip race.",
    region: "Asia",
    entityIds: [],
  },
  {
    id: "reg-003",
    title: "India's Renewable Capacity Crosses 200 GW Milestone in Push for Energy Transition",
    url: "https://www.thehindu.com/sci-tech/energy/india-renewable-200gw-2026/",
    sourceId: "hindu",
    publishedAt: "2026-07-25T05:15:00Z",
    category: "asia-pacific",
    summary: "Solar and wind installations surged past 200 GW, with India on track to meet its 2030 clean energy targets ahead of schedule.",
    region: "Asia",
    entityIds: ["aiib"],
  },
  {
    id: "reg-004",
    title: "Australia Signals Interest Rate Cut as Inflation Eases to Three-Year Low",
    url: "https://www.abc.net.au/news/2026-07-24/rba-rate-cut-inflation/",
    sourceId: "abc-au",
    publishedAt: "2026-07-24T01:00:00Z",
    category: "markets",
    summary: "The RBA indicated it could lower rates at the next meeting, with quarterly inflation falling to 2.4%, the lowest since 2023.",
    region: "Australia",
    entityIds: [],
  },
  {
    id: "reg-005",
    title: "EU Strikes Deal on Joint Gas Procurement to Replace Remaining Russian Supplies",
    url: "https://www.politico.eu/article/eu-joint-gas-procurement-russian-supplies-2026/",
    sourceId: "politico-eu",
    publishedAt: "2026-07-23T10:30:00Z",
    category: "trade-policy",
    summary: "Member states agreed to extend the joint purchasing platform, aiming to fully sever energy dependence on Russia by end of 2027.",
    region: "Europe",
    entityIds: [],
  },
  {
    id: "reg-006",
    title: "Sydney Morning Herald: Australia Secures Critical Minerals Deal with US and Japan",
    url: "https://www.smh.com.au/politics/critical-minerals-deal-us-japan-2026/",
    sourceId: "smh",
    publishedAt: "2026-07-22T22:00:00Z",
    category: "trade-policy",
    summary: "The trilateral agreement secures supply chains for rare earths and lithium, reducing reliance on Chinese processing for allied nations.",
    region: "Australia",
    entityIds: [],
  },
];

// 为 Mock 数据补充 sourceName 字段
const sourceNameMap = new Map(NEWS_SOURCES.map((s) => [s.id, s.name]));
export const MOCK_ARTICLES: NewsArticle[] = RAW_MOCK_ARTICLES.map((a) => ({
  ...a,
  sourceName: sourceNameMap.get(a.sourceId) ?? a.sourceId,
}));
